### ISSUE TITLE
En la portada debería estar el mapa de mapa.desastre.ec

### ISSUE THREAD

**Issue by andreslucena** [desastre-ecuador/AyudaEcuador#16]
Ahora mismo hay un problema de usabilidad con la web, ya que se enlaza a mapa.desastre.ec  en las secciones de "Reporta Tu Emergencia, Daño o Pedido de ayuda" y "Recursos Disponibles", pero en "Mapa" se muestra uno de Google Maps de Puntos de donación. 

Entiendo que se debería ingresar esos Puntos de donación en mapa.desastre.ec y embeberlo a esta web. 

Se está trabajando para que sea fácil embeberlo en este otro ticket: 
https://github.com/desastre-ecuador/mapa.desastre.ec/issues/43

**Comment by claucece** [comment]
El cambio esta en el branch 'cambio mapa'. Está esperando a que beta esté listo.

**Comment by jreyes33** [comment]
Los cambios del PR #26 fueron incorporados al `master`. Eso resuelve este _issue_.

 ¡Gracias!
