### ISSUE TITLE
Agregar mas herramientas externas en la sección de "Recursos"

### ISSUE THREAD

**Issue by crisguitar** [desastre-ecuador/AyudaEcuador#24]
Por ahora solo tenemos 2 cuando hay más recursos disponibles como las donaciones que recibe la cruz roja: http://www.cruzroja.org.ec/index.php/341-emergencia/759-donaciones-efectivo

El buscador de personas oficial que se esta compartiendo en los ministerios y otros.

**Comment by jreyes33** [comment]
Listo http://www.desastre.ec/#recursos
