### ISSUE TITLE
Los pasos para hacer un reporte estan mal

### ISSUE THREAD

**Issue by crisguitar** [desastre-ecuador/AyudaEcuador#25]
Reporte: "...acabo de ver que en la web de desastre ec en la sección reporta tu daño o emergencia, el segundo paso dice HAZ CLIC PARA ENVIAR UN INFORME, pero cambiaron la imagen y ya no corresponde ese texto, debería decir: HAZ CLIC PARA ENVIAR UN REPORTE"

Traten de seguir los pasos y van a darse cuenta que están mal.

**Comment by jreyes33** [comment]
Gracias por reportar. Ya está corregido.
