### ISSUE TITLE
Arreglar la flecha en el header

### ISSUE THREAD

**Issue by claucece** [desastre-ecuador/AyudaEcuador#28]
En algunas pantallas, sucede esto: 

<img width="1290" alt="screen shot 2016-04-25 at 9 21 10 am" src="https://cloud.githubusercontent.com/assets/8270508/14786980/21989b6e-0ac7-11e6-9624-adfc3eb8f21d.png">
<img width="1145" alt="screen shot 2016-04-25 at 9 21 16 am" src="https://cloud.githubusercontent.com/assets/8270508/14786985/2353d45a-0ac7-11e6-8b81-5ba2c678cb54.png">

**Comment by sauljabin** [comment]
Una mejora temporal 
https://github.com/desastre-ecuador/AyudaEcuador/commit/1f99a6639d2bdd4eed00c045952ee672882b3d2c

Revisar

**Comment by claucece** [comment]
Solved on 350a120
