### ISSUE TITLE
Link should open a new page on reports on map

### ISSUE THREAD

**Issue by claucece** [desastre-ecuador/AyudaEcuador#30]
It's been shown on the same page as seen here: 

<img width="1216" alt="screen shot 2016-04-25 at 4 50 07 pm" src="https://cloud.githubusercontent.com/assets/8270508/14800206/d489b0d0-0b05-11e6-9430-b8b3666ee8cf.png">

**Comment by jreyes33** [comment]
Está relacionado con desastre-ecuador/mapa.desastre.ec#89

**Comment by claucece** [comment]
Proper link has been pushed to develop branch on mapa.desastre.ec. @jreyes33 please, check in beta and merge to master. Commit number: 
36a92c1d868533560e99a5f0ca5e55a0ef4448d5

**Comment by jreyes33** [comment]
¡Gracias, @claucece, @sauljabin! Será subido en el siguiente despliegue a prod.
